base_url = "https://boskonf.no"
title = "Bergen Open Source"
description = "Årlig teknologikonferanse i Bergen om åpen kildekode og fri programvare"

default_language = "no"

compile_sass = true

build_search_index = false

[markdown]
highlight_code = false
external_links_target_blank = true

[translations]
pamelding = "Meld deg på!"
temabytter = "Temabytter"
kildekode = "Kildekode"
programmet = "Programmet"
sponsor = "Sponsor"
dager = "dager"
timer = "timer"
minutter = "minutter"
sekunder = "sekunder"
presentasjon = "Presentation"
slutter = "Slutter"
starter = "Starter"
stater_om = "starter om"

[languages.en]
build_search_index = true
title = "Bergen Open Source"
description = "Annual technology conference in Bergen on Open Source and Free Software"

[languages.en.translations]
pamelding = "Sign up & join!"
temabytter = "Theme switcher"
kildekode = "Source code"
programmet = "The program"
sponsor = "Sponsor"
dager = "days"
timer = "hours"
minutter = "minutes"
sekunder = "seconds"
presentasjon = "Presentation"
slutter = "Ends"
starter = "Starts"
starter_om = "starts in"

[extra]
nav = [
  { path = "@/arkiv/_index.md", type = "section", english=true },
  { path = "@/om.md", type = "page", english=true },
]

event_registration_link = "https://skjema.fribyte.no/index.php/371186"

is_active = false
