base_url = "https://boskonf.no"
title = "Bergen Open Source"

compile_sass = true

build_search_index = false

[markdown]
highlight_code = false

[extra]

nav = [
  { path = "@/program.md", type = "page" },
  { path = "@/bli-sponsor.md", type = "page" },
  { path = "@/om.md", type = "page" },
]

event_registration_link = "https://skjema.fribyte.no/index.php/371186"
