base_url = "https://example.com"
title = "Konferansen"

compile_sass = true

build_search_index = false

[markdown]
highlight_code = false

[extra]

nav = [
  { path = "@/program.md", type = "page" },
  { path = "@/bli-sponsor.md", type = "page" },
  { path = "@/om.md", type = "page" },
]

