base_url = "https://boskonf.no"
title = "Bergen Open Source"
description = "Årlig teknologikonferanse i Bergen om åpen kildekode og fri programvare"

compile_sass = true

build_search_index = false

[markdown]
highlight_code = false

[extra]

nav = [
  { path = "@/arkiv/_index.md", type = "section" },
  { path = "@/om.md", type = "page" },
]

event_registration_link = "https://skjema.fribyte.no/index.php/371186"

is_active = false
