import type { Program } from "./program";

const program2025: Program = {
  date: "2025-10-30",
  location: "Kvarteret, Bergen",
  address: "Olav Kyrres gate 49, 5015 Bergen",
  locationUrl: "https://www.openstreetmap.org/node/6137059358",
  schedule: [
    {
      title: "Dørene åpner",
      title_en: "Doors open",
      description: "Prøv å være tidlig ute!",
      description_en: "Try to arrive early!",
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "info",
    },
    {
      title: "Kort introduksjon",
      title_en: "Short introduction",
      description: "",
      description_en: "",
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "info",
    },
    {
      title: "Tale",
      title_en: "Speech",
      description: "Ledig tale slot",
      description_en: "Available speech slot",
      speaker: {
        name: "Ukjent taler",
        description: "Er dette deg? Ta kontakt!",
        description_en: "Is this you? Get in touch!",
        imageUrl: "",
      },
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "talk",
    },
    {
      title: "Tale",
      title_en: "Speech",
      description: "Ledig tale slot",
      description_en: "Available speech slot",
      speaker: {
        name: "Ukjent taler",
        description: "Er dette deg? Ta kontakt!",
        description_en: "Is this you? Get in touch!",
        imageUrl: "",
      },
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "talk",
    },
    {
      title: "Tale",
      title_en: "Speech",
      description: "Ledig tale slot",
      description_en: "Available speech slot",
      speaker: {
        name: "Ukjent taler",
        description: "Er dette deg? Ta kontakt!",
        description_en: "Is this you? Get in touch!",
        imageUrl: "",
      },
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "talk",
    },
    {
      title: "Mat",
      title_en: "Food",
      description: "Matpause",
      description_en: "Food break",
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "break",
    },
    {
      title: "Tale",
      title_en: "Speech",
      description: "Ledig tale slot",
      description_en: "Available speech slot",
      speaker: {
        name: "Ukjent taler",
        description: "Er dette deg? Ta kontakt!",
        description_en: "Is this you? Get in touch!",
        imageUrl: "",
      },
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "talk",
    },
    {
      title: "Tale",
      title_en: "Speech",
      description: "Ledig tale slot",
      description_en: "Available speech slot",
      speaker: {
        name: "Ukjent taler",
        description: "Er dette deg? Ta kontakt!",
        description_en: "Is this you? Get in touch!",
        imageUrl: "",
      },
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "talk",
    },
    {
      title: "Tale",
      title_en: "Speech",
      description: "Ledig tale slot",
      description_en: "Available speech slot",
      speaker: {
        name: "Ukjent taler",
        description: "Er dette deg? Ta kontakt!",
        description_en: "Is this you? Get in touch!",
        imageUrl: "",
      },
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "talk",
    },
    {
      title: "Takke for kvelden",
      description: "Takk for at du kom, de som vil delta på quiz blir igjen!",
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "info",
    },
    {
      title: "Kvelden ferdig",
      title_en: "The evening is finished",
      description: "Håper du hadde en fin kveld og likte årets konferanse :)",
      description_en:
        "We hope you had a nice evening and liked this years iteration of the conference :)",
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "info",
    },
  ],
  sponsors: [
    {
      "name": "Kantega",
      "logo": "/sponsors/kantega.svg",
      "url": "https://www.kantega.no/"
    },
    {
      name: "TietoEvry",
      logo: "/sponsors/tietoevry.svg",
      url: "https://www.tietoevry.com/",
    },
  ],
};

export default program2025;
