import type { Program } from "./program";

const program2025: Program = {
  date: "2025-10-30",
  location: "Kvarteret, Bergen",
  address: "Olav Kyrres gate 49, 5015 Bergen",
  locationUrl: "https://www.openstreetmap.org/node/6137059358",
  schedule: [
    {
      title: "Dørene åpner",
      title_en: "Doors open",
      description: "Prøv å være tidlig ute!",
      description_en: "Try to arrive early!",
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "info",
    },
    {
      title: "Kort introduksjon",
      title_en: "Short introduction",
      description: "",
      description_en: "",
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "info",
    },
    {
      title: "Bring your own cloud",
      title_en: "Bring your own cloud",
      description: "I lys av dagens svekkede tilitt til \"tech gigantene\" og fokuset på personvern og sikkerhet vil vi utforske et alternativ til \"spin det opp i {Insert cloud provider here}\" løsningen. I denne talken skal vi se litt på forskjellige open source verktøy og programvare en kan bruke til å bygge en kompetitiv hosting plattform. Må vi miste fordelene Aws/Azure/Google cloud gir? Er det spesifikke fordeler ved å bruke open source? Er dette kun noe for store bedrifter med egne devops team? Dette er spørsmål vi skal forsøke å besvare",
      description_en: "In light of todays weakened trust in the \"tech giants\" and the focus on privacy and security, we will explore an alternative to the \"spin it up in {Insert cloud provider here}\" solution. In this talk, we will take a look at various open source tools and software that can be used to build a competitive hosting platform. Do we have to give up the advantages that AWS/Azure/Google Cloud provide? Are there specific benefits to using open source? Is this only relevant for large companies with their own DevOps teams? These are questions we will attempt to answer.",
      speaker: {
        name: "Rolf Martin Glomsrud",
        description: "Utvikler, Frende",
        description_en: "Software Engineer, Frende",
        imageUrl: "speakers/Rolf-Glomsrud.jpg",
      },
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "talk",
    },
    {
      title: "Tale",
      title_en: "Speech",
      description: "Ledig tale slot",
      description_en: "Available speech slot",
      speaker: {
        name: "Ukjent taler",
        description: "Taler annonseres snart",
        description_en: "Speaker will be announced soon",
        imageUrl: "",
      },
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "talk",
    },
    {
      title: "Tale",
      title_en: "Speech",
      description: "Ledig tale slot",
      description_en: "Available speech slot",
      speaker: {
        name: "Ukjent taler",
        description: "Taler annonseres snart",
        description_en: "Speaker will be announced soon",
        imageUrl: "",
      },
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "talk",
    },
    {
      title: "Mat",
      title_en: "Food",
      description: "Matpause",
      description_en: "Food break",
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "break",
    },
    {
      title: "Tale",
      title_en: "Speech",
      description: "Ledig tale slot",
      description_en: "Available speech slot",
      speaker: {
        name: "Ukjent taler",
        description: "Taler annonseres snart",
        description_en: "Speaker will be announced soon",
        imageUrl: "",
      },
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "talk",
    },
    {
      title: "Tale",
      title_en: "Speech",
      description: "Ledig tale slot",
      description_en: "Available speech slot",
      speaker: {
        name: "Ukjent taler",
        description: "Taler annonseres snart",
        description_en: "Speaker will be announced soon",
        imageUrl: "",
      },
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "talk",
    },
    {
      title: "Tale",
      title_en: "Speech",
      description: "Ledig tale slot",
      description_en: "Available speech slot",
      speaker: {
        name: "Ukjent taler",
        description: "Taler annonseres snart",
        description_en: "Speaker will be announced soon",
        imageUrl: "",
      },
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "talk",
    },
    {
      title: "Takke for kvelden",
      description: "Takk for at du kom, de som vil delta på quiz blir igjen!",
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "info",
    },
    {
      title: "Kvelden ferdig",
      title_en: "The evening is finished",
      description: "Håper du hadde en fin kveld og likte årets konferanse :)",
      description_en:
        "We hope you had a nice evening and liked this years iteration of the conference :)",
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "info",
    },
  ],
  sponsors: [
    {
      "name": "Kantega",
      "logo": "/sponsors/kantega.svg",
      "url": "https://www.kantega.no/"
    },
    {
      name: "TietoEvry",
      logo: "/sponsors/tietoevry.svg",
      url: "https://www.tietoevry.com/",
    },
  ],
};

export default program2025;
