import type { Program } from "./program";

const program2025: Program = {
  date: "2025-10-30",
  location: "Kvarteret, Bergen",
  address: "Olav Kyrres gate 49, 5015 Bergen",
  locationUrl: "https://www.openstreetmap.org/node/6137059358",
  schedule: [
    {
      title: "Dørene åpner",
      title_en: "Doors open",
      description: "Prøv å være tidlig ute!",
      description_en: "Try to arrive early!",
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "info",
    },
    {
      title: "Kort introduksjon",
      title_en: "Short introduction",
      description: "",
      description_en: "",
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "info",
    },
    {
      title: "Bring your own cloud",
      title_en: "Bring your own cloud",
      description: "I lys av dagens svekkede tilitt til \"tech gigantene\" og fokuset på personvern og sikkerhet vil vi utforske et alternativ til \"spin det opp i {Insert cloud provider here}\" løsningen. I denne talken skal vi se litt på forskjellige open source verktøy og programvare en kan bruke til å bygge en kompetitiv hosting plattform. Må vi miste fordelene Aws/Azure/Google cloud gir? Er det spesifikke fordeler ved å bruke open source? Er dette kun noe for store bedrifter med egne devops team? Dette er spørsmål vi skal forsøke å besvare",
      description_en: "In light of todays weakened trust in the \"tech giants\" and the focus on privacy and security, we will explore an alternative to the \"spin it up in {Insert cloud provider here}\" solution. In this talk, we will take a look at various open source tools and software that can be used to build a competitive hosting platform. Do we have to give up the advantages that AWS/Azure/Google Cloud provide? Are there specific benefits to using open source? Is this only relevant for large companies with their own DevOps teams? These are questions we will attempt to answer.",
      speaker: {
        name: "Rolf Martin Glomsrud",
        description: "Utvikler, Frende",
        description_en: "Software Engineer, Frende",
        imageUrl: "/speakers/Rolf-Glomsrud.jpg",
      },
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "talk",
    },
    {
      title: "Has 20 years of experience lead to this?!",
      title_en: "Has 20 years of experience lead to this?!",
      description: "I over 24 år har jeg jobbet med, kost meg med og fått grå hår av frontend. Jeg deler mine erfaringer rundt dette, både det gode og det dårlige. Dette foredraget oppsummerer også hvor vi kommer fra innen frontend-utvikling, og hvor vi er på vei. Så hvis du er glad i litt frontend-nostalgi, er dette foredraget for deg.",
      description_en: "tl;dr; A talk/rant/beer in hand talk about my experience with frontend, from the 90s to today\nFor over 24 years I have played, enjoyed and gotten grey hairs doing frontend. I share my experiences around this, all the good and bad stuff.\nThis talk is also to summarize where we come from within frontend development, and where we are heading. So if you are into some frontend nostalgia, this talk is for you",
      speaker: {
        name: "Alexander Vassbotn Røyne-Helgesen",
        description: "Teknologileder og Frontend-ekspert",
        description_en: "Technology leader and Frontend expert",
        imageUrl: "/speakers/Alexander-Vassbotn.jpg",
      },
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "talk",
    },
    {
      title: "Model Context Protocol (MCP)",
      title_en: "Model Context Protocol (MCP)",
      description: "Model Context Protocol (MCP) er en åpen standard som gjør det mulig for AI-assistenter å koble seg til eksterne ressurser, og dermed utvide sin kontekst og funksjonalitet. MCP gir utviklere stor frihet i hvordan de kan sette opp sine assistenter. Presentasjonen tar for seg et konkret chatbot-problem som illustrerer begrensningene ved tradisjonelle, avlukkede språkmodeller, og gir en praktisk løsning med MCP.",
      description_en: "Model Context Protocol (MCP) is an open standard that enables AI assistants to connect to external resources, thereby expanding their context and functionality. MCP gives developers great flexibility in how they can set up their assistants. The presentation addresses a specific chatbot problem that illustrates the limitations of traditional, isolated language models, and provides a practical solution using MCP.",
      speaker: {
        name: "Johannes Jøsang",
        description: "Data Scientist++, Kantega",
        description_en: "Data Scientist++, Kantega",
        imageUrl: "/speakers/Johannes-Jøsang.jpg",
      },
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "talk",
    },
    {
      title: "Mat",
      title_en: "Food",
      description: "Matpause",
      description_en: "Food break",
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "break",
    },
    {
      title: "Skal du levere programvare, må du vite hva den består av. SBOM (Software Bill of Materials) i praksis: Hvorfor og hvordan",
      title_en: "If You're Delivering Software, You Need to Know What It's Made Of. SBOM (Software Bill of Materials) in Practice: Why and How",
      description: "12. desember 2027 er det for sent. Det er dagen etter at EUs Cyber Resilience Act (CRA) har fullt ut trådt i kraft. Hvis du er leverandør av “produkt med digitale komponenter”, må du ha full oversikt over og innsikt i alle komponenter og avhengigheter som inngår. Ellers er du ikke kvalifisert til å levere produktet i EU. Men hvis du som utvikler programvare kan svare “ja” når du får spørsmål av type “Vet du hva koden din gjør? Altså, vet du *alt* koden du skriver gjør?“, er du langt på vei i mål. Dette foredraget viser hvordan du går fra koder til kodeingeniør, og gir innsikt i praktisk bruk av “Software Bill of Materials” (SBOM) som er det sentrale verktøyet for å levere med innsikt og kvalitet.",
      description_en: "December 12, 2027 is too late. That's the day after the EU's Cyber Resilience Act (CRA) has come fully into effect. If you are a supplier of a “product with digital elements,” you must have complete oversight of and insight into all components and dependencies it contains. Otherwise, you are not qualified to deliver your product in the EU. But if, as a software developer, you can answer “yes” when asked: “Do you know what your code does? I mean, do you know everything the code you write does?” you are already well on your way. This presentation shows how to move from being a coder to becoming a code engineer, and provides insight into the practical use of the Software Bill of Materials (SBOM), the key tool for delivering with insight and quality.",
      speaker: {
        name: "Peter N. M. Hansteen",
        description: "Senior Technical Specialist, Tietoevry",
        description_en: "Senior Technical Specialist, Tietoevry",
        imageUrl: "/speakers/Peter-Hansteen.jpeg",
      },
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "talk",
    },
    {
      title: "Tale",
      title_en: "Speech",
      description: "Ledig tale slot",
      description_en: "Available speech slot",
      speaker: {
        name: "Ukjent taler",
        description: "Taler annonseres snart",
        description_en: "Speaker will be announced soon",
        imageUrl: "",
      },
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "talk",
    },
    {
      title: "Tale",
      title_en: "Speech",
      description: "Ledig tale slot",
      description_en: "Available speech slot",
      speaker: {
        name: "Ukjent taler",
        description: "Taler annonseres snart",
        description_en: "Speaker will be announced soon",
        imageUrl: "",
      },
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "talk",
    },
    {
      title: "Takke for kvelden",
      description: "Takk for at du kom, de som vil delta på quiz blir igjen!",
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "info",
    },
    {
      title: "Kvelden ferdig",
      title_en: "The evening is finished",
      description: "Håper du hadde en fin kveld og likte årets konferanse :)",
      description_en:
        "We hope you had a nice evening and liked this years iteration of the conference :)",
      image: "TODO: path to some image in static dir",
      from: "",
      to: "",
      type: "info",
    },
  ],
  sponsors: [
    {
      "name": "Kantega",
      "logo": "/sponsors/kantega.svg",
      "url": "https://www.kantega.no/"
    },
    {
      name: "TietoEvry",
      logo: "/sponsors/tietoevry.svg",
      url: "https://www.tietoevry.com/",
    },
  ],
};

export default program2025;
