import type { Program } from "./program";

const program2026: Program = {
  date: "Dato kommer",
  date_en: "TBA",
  location: "Lokale kommer",
  location_en: "TBA",
  address: "",
  locationUrl: "",
  schedule: [
    {
      title: "Dørene åpner",
      title_en: "Doors open",
      description: "Prøv å være tidlig ute!",
      description_en: "Try to arrive early!",
      image: "",
      from: "2026-10-29T16:30:00",
      to: "2026-10-29T17:00:00",
      type: "info",
    },
    {
      title: "Kort introduksjon",
      title_en: "Short introduction",
      description:
        "En kort introduksjon til Bergen Open Source-konferansen, med litt praktisk informasjon om kvelden.",
      description_en:
        "A brief introduction to the Bergen Open Source Conference, including some practical information about the evening.",
      image: "",
      from: "2026-10-29T17:00:00",
      to: "2026-10-29T17:10:00",
      type: "info",
    },
    {
      title: "Foredrag 1",
      title_en: "Talk 1",
      description: "Kommer snart...",
      description_en: "Coming soon...",
      speaker: {
        name: "Ditt navn her?",
        name_en: "Your name here?",
        description: "Foredragsholder annonseres snart",
        description_en: "Speaker to be announced",
      },
      image: "",
      from: "2026-10-29T17:10:00",
      to: "2026-10-29T17:30:00",
      type: "talk",
    },
    {
      title: "Foredrag 2",
      title_en: "Talk 2",
      description: "Kommer snart...",
      description_en: "Coming soon...",
      speaker: {
        name: "Ditt navn her?",
        name_en: "Your name here?",
        description: "Foredragsholder annonseres snart",
        description_en: "Speaker to be announced",
      },
      image: "",
      from: "2026-10-29T17:30:00",
      to: "2026-10-29T17:50:00",
      type: "talk",
    },
    {
      title: "Mat",
      title_en: "Food",
      description: "Matpause",
      description_en: "Food break",
      image: "",
      from: "2026-10-29T18:00:00",
      to: "2026-10-29T19:00:00",
      type: "break",
    },
    {
      title: "Foredrag 3",
      title_en: "Talk 3",
      description: "Kommer snart...",
      description_en: "Coming soon...",
      speaker: {
        name: "Ditt navn her?",
        name_en: "Your name here?",
        description: "Foredragsholder annonseres snart",
        description_en: "Speaker to be announced",
      },
      image: "",
      from: "2026-10-29T19:00:00",
      to: "2026-10-29T19:20:00",
      type: "talk",
    },
    {
      title: "Foredrag 4",
      title_en: "Talk 4",
      description: "Kommer snart...",
      description_en: "Coming soon...",
      speaker: {
        name: "Ditt navn her?",
        name_en: "Your name here?",
        description: "Foredragsholder annonseres snart",
        description_en: "Speaker to be announced",
      },
      image: "",
      from: "2026-10-29T19:20:00",
      to: "2026-10-29T19:40:00",
      type: "talk",
    },
    {
      title: "Foredrag 5",
      title_en: "Talk 5",
      description: "Kommer snart...",
      description_en: "Coming soon...",
      speaker: {
        name: "Ditt navn her?",
        name_en: "Your name here?",
        description: "Foredragsholder annonseres snart",
        description_en: "Speaker to be announced",
      },
      image: "",
      from: "2026-10-29T19:40:00",
      to: "2026-10-29T20:00:00",
      type: "talk",
    },
    {
      title: "Foredrag 6",
      title_en: "Talk 6",
      description: "Kommer snart...",
      description_en: "Coming soon...",
      speaker: {
        name: "Ditt navn her?",
        name_en: "Your name here?",
        description: "Foredragsholder annonseres snart",
        description_en: "Speaker to be announced",
      },
      image: "",
      from: "2026-10-29T20:00:00",
      to: "2026-10-29T20:20:00",
      type: "talk",
    },
    {
      title: "Takk for kvelden",
      title_en: "Thank you for the evening",
      description: "Takk for at du ble med på Bergen Open Source-konferansen!",
      description_en:
        "Thank you for attending the Bergen Open Source Conference!",
      image: "",
      from: "2026-10-29T20:20:00",
      to: "2026-10-29T20:35:00",
      type: "info",
    },
  ],
  sponsors: [
    {
      name: "knowit",
      name_en: "knowit",
      logo: "/sponsors/knowit.svg",
      url: "https://www.knowit.no/",
    },
    {
      name: "NDLA",
      name_en: "NDLA",
      logo: "/sponsors/ndla.png",
      url: "https://ndla.no/",
    },
    {
      name: "SodaCompagniet AS",
      name_en: "SodaCompagniet AS",
      logo: "/sponsors/olacola.png",
      url: "https://sodaco.no/",
    },
    {
      name: "Din logo her?",
      name_en: "Your logo here?",
      logo: "",
      url: "/sponsor",
    }
  ],
};

export default program2026;
