name: Build and deploy to production
on: 
  push:
    branches: 
      - main
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: taiki-e/install-action@v2
      with:
        tool: zola@0.17.1
    - name: Check Zola links
      run: |
        zola check
    - name: Build Zola site
      run: |
        zola build
    - name: rsync files
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete
        path: public/
        remote_path: /home/fribyte/konferanse/public
        remote_host: ${{ secrets.SERVER_IP }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
        remote_port: ${{ secrets.PORT }}
