# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Frontend Build and Push to DockerHub

on:
  push:
    # branches: ["main"] # Revert to main when merged
    branches: ["*"]
  pull_request:
    # branches: ["main"] # Revert to main when merged
    branches: ["*"]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: fribyte/boskonf.no

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          tags: fribyte/boskonf.no:latest
          build-args: |
            APP_BUILD_DATE=${{ github.event.repository.updated_at}}
